### ISSUE TITLE
KeyError: 'Bitacora'

### ISSUE THREAD

**Issue by BFeldmeyer** [IAndreu/Gene-annotation-pipeline#1]
Hi there,
I am trying to run your pipeline and after installing phython3 and the new panda version I get the following error. 

/bin/Gene-annotation-pipeline/Scripts/run_analysis.py
---------------------------------
Traceback (most recent call last):
  File "/cluster/software/python3/python_374/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Bitacora'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/bin/Gene-annotation-pipeline/Scripts/run_analysis.py", line 83, in <module>
    Bitacora= [df['Bitacora'][i] for i in range(len(df))]
  File "/bin/Gene-annotation-pipeline/Scripts/run_analysis.py", line 83, in <listcomp>
    Bitacora= [df['Bitacora'][i] for i in range(len(df))]
  File "/cluster/software/python3/python_374/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/cluster/software/python3/python_374/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'Bitacora'

Do you have any suggestions on what the problem might be?
Moreover, is there a new link/path to the skript and followup workflow? The lschrader/GAGA/... does not exist any more.

Thanks for your help!

**Comment by git-hobo** [comment]
For anyone coming across this problem in 2025:
The gene_families_info.xlsx also needs a column called 'Bitacora' and the values can be "full" | "genome" | "protein" | "No" . Any other value (such as "Yes") results in "Bitacora not runned" in the genecounts_summary.txt
